### ISSUE TITLE
[bug] server destroy_idle_sessions hang when shutdown

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#1082]
**Summary**

fuse-query server often hang when CTRL+C.

**How to reproduce**
Not sure how to reproduce it, I have two connection, one is from MySQL client and another is ClickHouse client, after a long while(one night) the server can not be CTRL+C and hang.

**Error message and/or stacktrace**
server CTRL+C:
```
bohu@thinkpad:~/github/datafuselabs/datafuse$ ./target/release/fuse-query 
[2021-07-17T13:02:59Z INFO  fuse_query] Config { log_level: "INFO", log_dir: "./_logs", num_cpus: 16, mysql_handler_host: "127.0.0.1", mysql_handler_port: 3307, max_active_sessions: 256, clickhouse_handler_host: "127.0.0.1", clickhouse_handler_port: 9000, flight_api_address: "127.0.0.1:9090", http_api_address: "127.0.0.1:8080", metric_api_address: "127.0.0.1:7070", store_api_address: "127.0.0.1:9191", store_api_username: ******, store_api_password: ******, config_file: "" }
[2021-07-17T13:02:59Z INFO  fuse_query] FuseQuery v-0.1.0-bfe0e66-simd(1.55.0-nightly-2021-07-17T12:29:11.324190641+00:00), Allocator: default
[2021-07-17T13:02:59Z INFO  fuse_query] MySQL handler listening on 127.0.0.1:3307, Usage: mysql -h127.0.0.1 -P3307
[2021-07-17T13:02:59Z INFO  fuse_query] ClickHouse handler listening on 127.0.0.1:9000, Usage: clickhouse-client --host 127.0.0.1 --port 9000
[2021-07-17T13:02:59Z INFO  fuse_query] Metric API server listening on 127.0.0.1:7070
[2021-07-17T13:02:59Z INFO  fuse_query] HTTP API server listening on 127.0.0.1:8080
[2021-07-17T13:02:59Z INFO  fuse_query] RPC API server listening on 127.0.0.1:9090
[2021-07-17T13:02:59Z INFO  fuse_query] Ready for connections.
[2021-07-17T13:03:13Z INFO  fuse_query::sessions::context] Destroy FuseQueryContext
[2021-07-17T13:03:31Z INFO  fuse_query::sessions::context] Destroy FuseQueryContext
[2021-07-17T13:03:32Z INFO  fuse_query::sessions::context] Destroy FuseQueryContext
[2021-07-17T13:04:34Z INFO  fuse_query::sessions::context] Destroy FuseQueryContext
^C[2021-07-18T01:55:22Z INFO  fuse_query::servers::server] Received termination signal.
[2021-07-18T01:55:22Z INFO  fuse_query::servers::server] You can press Ctrl + C again to force shutdown.
[2021-07-18T01:55:22Z INFO  fuse_query::sessions::sessions] Waiting for current connections to close.
```

gdb stack:
```
(gdb) bt
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00005611d962fd2c in parking_lot_core::thread_parker::imp::ThreadParker::futex_wait (self=0x7fc376ce2760, ts=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.3/src/thread_parker/linux.rs:112
#2  <parking_lot_core::thread_parker::imp::ThreadParker as parking_lot_core::thread_parker::ThreadParkerT>::park (self=0x7fc376ce2760)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.3/src/thread_parker/linux.rs:66
#3  parking_lot_core::parking_lot::park::{{closure}} (thread_data=<optimized out>)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.3/src/parking_lot.rs:611
#4  parking_lot_core::parking_lot::with_thread_data (f=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.3/src/parking_lot.rs:183
#5  parking_lot_core::parking_lot::park (key=94634686609104, validate=..., timed_out=..., park_token=..., timeout=..., before_sleep=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot_core-0.8.3/src/parking_lot.rs:576
#6  parking_lot::raw_rwlock::RawRwLock::lock_common (self=0x5611dae0f6d0, timeout=..., token=..., try_lock=..., validate_flags=8)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.1/src/raw_rwlock.rs:1110
#7  parking_lot::raw_rwlock::RawRwLock::lock_shared_slow (self=0x5611dae0f6d0, recursive=false, timeout=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.1/src/raw_rwlock.rs:714
#8  0x00005611d997c563 in <parking_lot::raw_rwlock::RawRwLock as lock_api::rwlock::RawRwLock>::lock_shared (self=0x5611dae0f6d0)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/parking_lot-0.11.1/src/raw_rwlock.rs:110
#9  lock_api::rwlock::RwLock<R,T>::read (self=0x5611dae0f6d0) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/lock_api-0.4.4/src/rwlock.rs:429
#10 common_infallible::rwlock::RwLock<T>::read (self=0x5611dae0f6d0) at /home/bohu/github/datafuselabs/datafuse/common/infallible/src/rwlock.rs:22
#11 fuse_query::sessions::sessions::SessionManager::destroy_idle_sessions (sessions=<optimized out>) at fusequery/query/src/sessions/sessions.rs:153
#12 0x00005611d965d7a1 in fuse_query::sessions::sessions::SessionManager::shutdown::{{closure}} ()
    at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/sessions/sessions.rs:127
#13 <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=<optimized out>)
    at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/core/src/future/mod.rs:80
#14 fuse_query::servers::server::ShutdownHandle::shutdown::{{closure}} () at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/servers/server.rs:55
#15 <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=<optimized out>)
    at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/core/src/future/mod.rs:80
#16 fuse_query::servers::server::ShutdownHandle::wait_for_termination_request::{{closure}} ()
    at /home/bohu/github/datafuselabs/datafuse/fusequery/query/src/servers/server.rs:69
#17 <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=<optimized out>)
    at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/core/src/future/mod.rs:80
#18 fuse_query::main::{{closure}} () at fusequery/query/src/bin/fuse-query.rs:124
#19 0x00005611d9668173 in <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll (self=..., cx=0x7fff60fe9188)
    at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/core/src/future/mod.rs:80
#20 tokio::park::thread::CachedParkThread::block_on::{{closure}} () at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/park/thread.rs:263
#21 tokio::coop::with_budget::{{closure}} (cell=0xfffffffffffffe00) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:106
#22 std::thread::local::LocalKey<T>::try_with (self=<optimized out>, f=...) at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/thread/local.rs:399
#23 std::thread::local::LocalKey<T>::with (self=<optimized out>, f=...) at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/thread/local.rs:375
#24 0x00005611d966b55d in tokio::coop::with_budget (budget=..., f=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:99
#25 tokio::coop::budget (f=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/coop.rs:76
#26 tokio::park::thread::CachedParkThread::block_on (self=0x7fff60fe9418, f=...)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/park/thread.rs:263
#27 0x00005611d965af0e in tokio::runtime::enter::Enter::block_on (self=0x7fff60fe9418, f=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/enter.rs:151
#28 tokio::runtime::thread_pool::ThreadPool::block_on (self=<optimized out>, future=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/thread_pool/mod.rs:71
#29 0x00005611d9661028 in tokio::runtime::Runtime::block_on (self=<optimized out>, future=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.8.1/src/runtime/mod.rs:452
#30 0x00005611d966baa6 in fuse_query::main () at fusequery/query/src/bin/fuse-query.rs:126
(gdb) 

```

**Comment by zhang2014** [comment]
It fixed in #1075

**Comment by BohuTANG** [comment]
Hi @zhang2014 ,
I found another hang with master branch when running a long query:
client:
```
mysql> SELECT max(number), sum(number) FROM numbers_mt(10000000000) GROUP BY number % 3, number % 4, number % 5;
```

Server can't quit by CTRL+C:
```
^C[2021-07-20T03:52:56Z INFO  fuse_query::servers::server] Received termination signal.
[2021-07-20T03:52:56Z INFO  fuse_query::servers::server] You can press Ctrl + C again to force shutdown.
^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

**Comment by zhang2014** [comment]
What is GDB stack?

**Comment by BohuTANG** [comment]
I can't  re-produce it now with the master branch.
