### ISSUE TITLE
Flaky tests: UT failed with message "been running for over 60 seconds"

### ISSUE THREAD

**Issue by dantengsky** [datafuselabs/datafuse#1205]
**Summary**

cargo test failed **frequently** with error  message: " $TEST_CASE_NAME has been running for over 60 seconds"

Some observations may be helpful:

- seems it is related to multi-thread
   when testing with `--test-threads 1`,  no errors were found (repeated for many times)
  `cargo test -- --test-threads 1 --nocapture`
- testing of a single case works just fine
  `cargo test $CASE_NAME` 
- `sled`, or  the way we used `sled` is at least one of the reasons
   as test log message tells: 
    > 'tokio-runtime-worker failed to make_stable after 30 seconds. waiting to stabilize lsn 187, current stable -1 intervals: StabilityIntervals { fsynced_ranges: [], batches: {}, stable_lsn: -1 }'
   

**How to reproduce**

`cargo test -- --nocapture`

**Error message and/or stacktrace**

~~~
test api::rpc::flight_service_test::test_do_append has been running for over 60 seconds
test api::rpc::flight_service_test::test_flight_create_database has been running for over 60 seconds
test api::rpc::flight_service_test::test_flight_create_get_table has been running for over 60 seconds
test api::rpc::flight_service_test::test_flight_generic_kv has been running for over 60 seconds
test api::rpc::flight_service_test::test_flight_get_database_meta_ddl_db has been running for over 60 seconds
test api::rpc::flight_service_test::test_flight_get_database_meta_ddl_table has been running for over 60 seconds
test api::rpc::flight_service_test::test_flight_get_database_meta_empty_db has been running for over 60 seconds
test api::rpc::flight_service_test::test_scan_partition has been running for over 60 seconds
test dfs::distributed_fs_test::test_distributed_fs_single_node_list has been running for over 60 seconds
test dfs::distributed_fs_test::test_distributed_fs_single_node_read_all has been running for over 60 seconds
test executor::action_handler_test::test_action_handler_add_database has been running for over 60 seconds
test executor::action_handler_test::test_action_handler_create_table has been running for over 60 seconds
thread 'dfs::distributed_fs_test::test_distributed_fs_single_node_read_all' panicked at 'dfs::distributed_fs_test::test_distributed_fs_single_node_read_all failed to make_stable after 30 seconds. waiting to stabilize lsn 187, current stable -1 intervals: StabilityIntervals { fsynced_ranges: [], batches: {}, stable_lsn: -1 }', /home/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/sled-0.34.6/src/pagecache/iobuf.rs:986:21
test executor::action_handler_test::test_action_handler_do_pull_file has been running for over 60 seconds
test executor::action_handler_test::test_action_handler_drop_database has been running for over 60 seconds
thread 'tokio-runtime-worker' panicked at 'tokio-runtime-worker failed to make_stable after 30 seconds. waiting to stabilize lsn 187, current stable 70 intervals: StabilityIntervals { fsynced_ranges: [], batches: {}, stable_lsn: 70 }', /home/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/sled-0.34.6/src/pagecache/iobuf.rs:986:21
stack backtrace:
thread 'tokio-runtime-worker' panicked at 'tokio-runtime-worker failed to make_stable after 30 seconds. waiting to stabilize lsn 187, current stable 70 intervals: StabilityIntervals { fsynced_ranges: [], batches: {}, stable_lsn: 70 }', /home/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/sled-0.34.6/src/pagecache/iobuf.rs:986:21
thread 'tokio-runtime-worker' panicked at 'tokio-runtime-worker failed to make_stable after 30 seconds. waiting to stabilize lsn 187, current stable 70 intervals: StabilityIntervals { fsynced_ranges: [], batches: {}, stable_lsn: 70 }', /home/xxx/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/sled-0.34.6/src/pagecache/iobuf.rs:986:21
   0:     0x56467cb1a7e0 - std::backtrace_rs::backtrace::libunwind::trace::h4e80f45db05e9df0
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56467cb1a7e0 - std::backtrace_rs::backtrace::trace_unsynchronized::h9db62a3d3587f6c3
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56467cb1a7e0 - std::sys_common::backtrace::_print_fmt::h2fafbe52c9090591
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56467cb1a7e0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7d41ae04358c516d
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56467cb4245c - core::fmt::write::h968e6400cbc51d6a
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/core/src/fmt/mod.rs:1112:17
   5:     0x56467cb12fc5 - std::io::Write::write_fmt::h2eaa97c6f8c9e829
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/io/mod.rs:1640:15
   6:     0x56467cb1cfcb - std::sys_common::backtrace::_print::h601a6bc581f240d5
                               at /rustc/868c702d0c9a471a28fb55f0148eb1e3e8b1dcc5/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56467cb1cfcb - std::sys_common::backtrace::print::h8b96e15ba64b8e64
~~~

**Comment by drmingdrmer** [comment]
- [x] Fixed in #1231 
Confirmed on my laptop and by CI.
If there still is similar timeout problem, feel free to reopen it.
