### ISSUE TITLE
Remote table not work for query with aggregation

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#1487]
**How to reproduce**

 
```
DROP DATABASE IF EXISTS db1;
CREATE DATABASE db1;
USE db1;

CREATE TABLE IF NOT EXISTS t1(a UInt32, b UInt64, c String);
insert into t1 (a,b,c) values ( 1, 1, '1' ), (2, 2, '"2"-"2"');

select * from t1;  --works 
SELECT sum(a) from t1; -- not work

DROP TABLE t1;
DROP DATABASE db1;

```

cc @dantengsky

**Comment by dantengsky** [comment]
roger that

**Comment by dantengsky** [comment]
after PR #1484, cannot reproduce. 
I will add the case you provide to the integration test

**Comment by sundy-li** [comment]
That's weird, I still encounter this.

```
mysql> insert into t1 (a,b,c) values ( 1, 1, '1' ), (2, 2, '"2"-"2"');
Query OK, 0 rows affected (0.07 sec)

mysql> SELECT * FROM t1;
+------+------+---------+
| a    | b    | c       |
+------+------+---------+
|    1 |    1 | 1       |
|    2 |    2 | "2"-"2" |
+------+------+---------+
2 rows in set (0.15 sec)

mysql> select sum(a) from t1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    8
Current database: db1


ERROR 1105 (HY000): Code: 25, displayText = Unknown table: 't1'.
mysql>
```

```
[2021-08-17T06:24:47Z INFO  common_flights::store_client] do_action: resp: {"table_id":3,"db":"","name":"","schema":{"fields":[{"name":"a","data_type":"UInt32","nullable":false},{"name":
"b","data_type":"UInt64","nullable":false},{"name":"c","data_type":"Utf8","nullable":false}]}}
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/sundy/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/647fddb/src/io/ipc/read/deserialize.rs:302:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by dantengsky** [comment]
I found similar problems in CI testing, digging into it.

FYI:  https://github.com/datafuselabs/datafuse/pull/1489/checks?check_run_id=3347526750

**Comment by dantengsky** [comment]
> after PR #1484, cannot reproduce.
> I will add the case you provide to the integration test

"cannot reproduce" in local dev box, problems do exist in CI env

**Comment by dantengsky** [comment]
@sundy-li  
would u please do me a favor and run `fuse-store` with `RUST_BACKTRACE=1`? I can not reproduce this issue in my dev env.

**Comment by dantengsky** [comment]
O, wait, does 
> Lost connection to MySQL server during query
mean that there is a Query panic?

**Comment by sundy-li** [comment]
> O, wait, does
> 
> > Lost connection to MySQL server during query
> 
> mean that there is a Query panic as well?

Yes, and there is panic in query.

**Comment by dantengsky** [comment]
Maybe panicked in deserialization of table schema... 
> thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/sundy/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/647fddb/src/io/ipc/read/deserialize.rs:302:46

would u please run query with RUST_BACKTRACE ?

**Comment by dantengsky** [comment]
@sundy-li  I can re-produce the problem now. please ignore the RUST_BACKTRACE things, I will touch you if I need further helps from you, thanks man

**Comment by sundy-li** [comment]
Seems something related to flight of arrow2
```
  23: arrow2::io::ipc::read::common::read_record_batch
             at /home/sundy/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/647fddb/src/io/ipc/read/common.rs:57:18
  24: arrow_flight::utils::flight_data_to_arrow_batch::{{closure}}
             at /home/sundy/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/647fddb/arrow-flight/src/utils.rs:165:13
  25: core::result::Result<T,E>::map
             at /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/core/src/result.rs:766:25
  26: arrow_flight::utils::flight_data_to_arrow_batch
             at /home/sundy/.cargo/git/checkouts/arrow2-6249446b5f8db6f7/647fddb/arrow-flight/src/utils.rs:159:5
  27: common_flights::impls::storage_api_impl::<impl common_store_api::storage_api::StorageApi for common_flights::store_client::StoreClient>::read_partition::{{closure}}::{{closure}}::{
{closure}}
             at ./common/flights/src/impls/storage_api_impl.rs:95:21
  28: core::result::Result<T,E>::and_then
             at /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/core/src/result.rs:966:22
  29: common_flights::impls::storage_api_impl::<impl common_store_api::storage_api::StorageApi for common_flights::store_client::StoreClient>::read_partition::{{closure}}::{{closure}}
             at ./common/flights/src/impls/storage_api_impl.rs:93:13
  30: <T as futures_util::fns::FnMut1<A>>::call_mut
             at /home/sundy/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/futures-util-0.3.16/src/fns.rs:28:9
  31: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next::{{closure}}
             at /home/sundy/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/futures-util-0.3.16/src/stream/stream/map.rs:59:33
  32: core::option::Option<T>::map
             at /rustc/e3b1c12becebd21d88ca9f4364d7db8d1d380c18/library/core/src/option.rs:836:29
  33: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
             at /home/sundy/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/futures-util-0.3.16/src/stream/stream/map.rs:59:21
  34: <core::pin::Pin<P> as futures_core::stream::Stream>::poll_next
             at /home/sundy/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/futures-core-0.3.16/src/stream.rs:120:9
  35: <futures_util::stream::stream::flatten::Flatten<St,<St as futures_core::stream::Stream>::Item> as futures_core::stream::Stream>::poll_next
             at /home/sundy/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/futures-util-0.3.16/src/stream/stream/flatten.rs:50:44
  36: <futures_util::stream::stream::Flatten<St> as futures_core::stream::Stream>::poll_next
```

**Comment by dantengsky** [comment]
roger
