### ISSUE TITLE
`datafuse/tests/./datafuse-test` TypeError: '<' not supported between instances of 'tuple' and 'int'

### ISSUE THREAD

**Issue by dust1** [datafuselabs/datafuse#1676]
Make sure that `git diff` result is empty and you've just pulled fresh master, and run first:
```text
$ make stateless-test
```

**Operating system**

Python Version : 3.9.5
OS : Mac OS Mojava 10.14.6
git version 2.14.1

**rust version**
```text
$ rustc --version
rustc 1.56.0-nightly (e3b1c12be 2021-08-02)

$ cargo --version
cargo 1.55.0-nightly (d21c22870 2021-07-26)
```

**Datafuse git version**
git commit id : 7a3bfc5620e545333ca4e35c71ac849b421b74fc

**Other**
Error Info:
```
Starting datafuse-test
Traceback (most recent call last):
  File "/Users/kous/myProjects/rustproject/datafuse/tests/./datafuse-test", line 481, in <module>
    main(args)
  File "/Users/kous/myProjects/rustproject/datafuse/tests/./datafuse-test", line 345, in main
    for suite in sorted(os.listdir(base_dir), key=sute_key_func):
TypeError: '<' not supported between instances of 'tuple' and 'int'
make: *** [stateless-test] Error 1
```
but when I execute the relevant statement in the py file, he is correct:
```
import os
def sute_key_func(item):
        if -1 == item.find('_'):
            return 99998
        prefix, suffix = item.split('_', 1)
        try:
            return int(prefix), suffix
        except ValueError:
            return 99997
 for suite in sorted(os.listdir(base_dir), key=sute_key_func):
        print(suite)
```

**Comment by drmingdrmer** [comment]
```
    def sute_key_func(item):
        if -1 == item.find('_'):
            return 99998
        prefix, suffix = item.split('_', 1)
        try:
            return int(prefix), suffix
        except ValueError:
            return 99997
```
These two return value must be all tuple: `(int, string)`. `99997` is only an int, which causes this issue.
`return (99997, "")` should fix this issue
