### ISSUE TITLE
ClickHouse client: Cannot load data for command line suggestions

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#336]
(you don't have to strictly follow this form)

**Describe the bug**

Using ClickHouse client connect to Datafuse, got first error:
Client error:
```
datafuse :) Cannot load data for command line suggestions: Code: 210, e.displayText() = DB::NetException: Connection reset by peer, while reading from socket (127.0.0.1:9000): while receiving packet from localhost:9000 (version 21.3.1.5944 (official build))

```

Datafuse Error:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Other("invalid utf-8 sequence of 1 bytes from index 1")', fusequery/query/src/servers/clickhouse/clickhouse_handler.rs:153:84
stack backtrace:
   0:     0x56540d4fbe90 - std::backtrace_rs::backtrace::libunwind::trace::h4dee703919bfd40a
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56540d4fbe90 - std::backtrace_rs::backtrace::trace_unsynchronized::h457e839f1a563e20
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56540d4fbe90 - std::sys_common::backtrace::_print_fmt::h86a55fb30f8393c8
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56540d4fbe90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7b3d6cac46d277e1
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x56540d51bc9f - core::fmt::write::h127419eb46f2ecc9
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/fmt/mod.rs:1092:17
   5:     0x56540d4f4eb2 - std::io::Write::write_fmt::h6010cfbb4726588b
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/io/mod.rs:1572:15
   6:     0x56540d4fdeb5 - std::sys_common::backtrace::_print::h79b4f9652330cc9d
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56540d4fdeb5 - std::sys_common::backtrace::print::h330bb326a76af8cf
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56540d4fdeb5 - std::panicking::default_hook::{{closure}}::heb6a42a7d50a472e
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:208:50
   9:     0x56540d4fd973 - std::panicking::default_hook::h17e521ba6d68d6e1
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:225:9
  10:     0x56540d4fe45d - std::panicking::rust_panic_with_hook::h70db735e3a6e70cb
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:591:17
  11:     0x56540d4fe057 - std::panicking::begin_panic_handler::{{closure}}::h777c71c8e5a7e25c
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:497:13
  12:     0x56540d4fc34c - std::sys_common::backtrace::__rust_end_short_backtrace::h3e9bf30168899554
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x56540d4fdfb9 - rust_begin_unwind
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/panicking.rs:493:5
  14:     0x56540c946901 - core::panicking::panic_fmt::h5322a082d19786c3
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/panicking.rs:92:14
  15:     0x56540c9467f3 - core::option::expect_none_failed::h354eaa93a51d71b8
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/option.rs:1329:5
  16:     0x56540ca88c4c - core::result::Result<T,E>::unwrap::h60bf6882a3d78d67
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
  17:     0x56540ca88c4c - fuse_query::servers::clickhouse::clickhouse_handler::ClickHouseHandler::start::{{closure}}::h8000ab3306ebb42c
                               at /home/bohu/github/rustwork/datafuselabs/datafuse/fusequery/query/src/servers/clickhouse/clickhouse_handler.rs:153:17
  18:     0x56540ca88c4c - <F as threadpool::FnBox>::call_box::hf6060cc681750f39
                               at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/threadpool-1.8.1/src/lib.rs:95:9
  19:     0x56540d139b89 - threadpool::spawn_in_pool::{{closure}}::h17fe83866e980cb9
                               at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/threadpool-1.8.1/src/lib.rs:769:17
  20:     0x56540d139b89 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7535521d72299fc5
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  21:     0x56540d13a37e - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h25daf16375208759
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:474:17
  22:     0x56540d13a37e - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h54815769971287b0
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:344:9
  23:     0x56540d13a37e - std::panicking::try::do_call::hf7d0cf59d9d6033c
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:379:40
  24:     0x56540d13a37e - std::panicking::try::h8c46663364b0a177
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:343:19
  25:     0x56540d13a37e - std::panic::catch_unwind::hb2f319f48461d0d5
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panic.rs:431:14
  26:     0x56540d13a37e - std::thread::Builder::spawn_unchecked::{{closure}}::hc9983b848b967485
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/thread/mod.rs:473:30
  27:     0x56540d13a37e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5aa95230e0200cb7
                               at /home/bohu/.rustup/toolchains/nightly-2021-03-24-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  28:     0x56540d5015b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7f7bdfc757a1add0
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/alloc/src/boxed.rs:1546:9
  29:     0x56540d5015b3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha294ad0fb99e9b3a
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/alloc/src/boxed.rs:1546:9
  30:     0x56540d5015b3 - std::sys::unix::thread::Thread::new::thread_start::h4614854ae73cd6b0
                               at /rustc/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sys/unix/thread.rs:71:17
  31:     0x7f58badee609 - start_thread
  32:     0x7f58babbe293 - clone
  33:                0x0 - <unknown>

```

**Comment by sundy-li** [comment]
We can add `--disable_suggestion`, or we maintain another version of `clickhouse-client` that disable suggestion by default.

```
❯ clickhouse-client --help | grep suggest
  -A [ --disable_suggestion ]                                      Disable loading suggestion data. Note that suggestion data is loaded
                                                                   it is reasonable to disable suggestion if you want to paste a query
  --suggestion_limit arg (=10000)                                  Suggestion limit for how many databases, tables and columns to fetch.

~ ❯
```

**Comment by BohuTANG** [comment]
> We can add `--disable_suggestion`, or we maintain another version of `clickhouse-client` that disable suggestion by default.
> 
> ```
> ❯ clickhouse-client --help | grep suggest
>   -A [ --disable_suggestion ]                                      Disable loading suggestion data. Note that suggestion data is loaded
>                                                                    it is reasonable to disable suggestion if you want to paste a query
>   --suggestion_limit arg (=10000)                                  Suggestion limit for how many databases, tables and columns to fetch.
> 
> ~ ❯
> ```

Ok, disable suggestions by design.
