### ISSUE TITLE
ShowTables not work

### ISSUE THREAD

**Issue by sundy-li** [datafuselabs/datafuse#381]
**Describe the bug**
```
show tables 

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 1', common/planners/src/plan_display.rs:85:37
```

**Additional context**

`show tables` is rewritten to `SELECT name FROM system.tables order by database, name` , but `database` column is not in projection, so error occurs.

**Comment by BohuTANG** [comment]
Here need a stateless test.
It's time to kick off our powerful integration and fuzz test framework.
cc @zhang2014 @ZhiHanZ

**Comment by BohuTANG** [comment]
Log:
```
[2021-04-24T04:58:17Z ERROR fuse_query::servers::mysql::mysql_handler] ResultError Unsupported Function: DATABASE
    
    Stack backtrace:
       0: anyhow::private::new_adhoc
                 at /home/bohu/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/anyhow-1.0.40/src/lib.rs:632:36
       1: common_functions::function_factory::FunctionFactory::get::{{closure}}
                 at /home/bohu/github/rustwork/datafuse/common/functions/src/function_factory.rs:41:28
       2: core::option::Option<T>::ok_or_else
                 at /home/bohu/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:593:25
       3: common_functions::function_factory::FunctionFactory::get
                 at /home/bohu/github/rustwork/datafuse/common/functions/src/function_factory.rs:39:23
       4: common_planners::plan_expression::ExpressionPlan::to_function_with_depth
                 at /home/bohu/github/rustwork/datafuse/common/planners/src/plan_expression.rs:79:32
       5: common_planners::plan_expression::ExpressionPlan::to_function
                 at /home/bohu/github/rustwork/datafuse/common/planners/src/plan_expression.rs:98:9
       6: common_planners::plan_expression::ExpressionPlan::has_aggregator
                 at /home/bohu/github/rustwork/datafuse/common/planners/src/plan_expression.rs:111:12
       7: fuse_query::sql::plan_parser::PlanParser::select_to_plan
                 at /home/bohu/github/rustwork/datafuse/fusequery/query/src/sql/plan_parser.rs:205:16
       8: fuse_query::sql::plan_parser::PlanParser::query_to_plan
                 at /home/bohu/github/rustwork/datafuse/fusequery/query/src/sql/plan_parser.rs:172:17
       9: fuse_query::sql::plan_parser::PlanParser::sql_statement_to_plan
                 at /home/bohu/github/rustwork/datafuse/fusequery/query/src/sql/plan_parser.rs:84:40
      10: fuse_query::sql::plan_parser::PlanParser::statement_to_plan
                 at /home/bohu/github/rustwork/datafuse/fusequery/query/src/sql/plan_parser.rs:60:42
      11: fuse_query::sql::plan_parser::PlanParser::build_from_sql
```
