### ISSUE TITLE
[shutdown] can not force shutdown

### ISSUE THREAD

**Issue by BohuTANG** [datafuselabs/datafuse#899]
(you don't have to strictly follow this form)

**How to reproduce**
Make a panic for a system table, such as `system.functions` table:
```
 async fn read(&self, _ctx: FuseQueryContextRef) -> Result<SendableDataBlockStream> {
    todo!()
}
```

clickhouse client:
```
> select * from system.functions;
```

server side is hang and can not force shutdown.

**Error message and/or stacktrace**

fuse-query log:
```
thread '<unnamed>' panicked at 'not yet implemented', fusequery/query/src/datasources/system/tracing_table_stream.rs:27:9
^C[2021-06-25T00:37:41Z INFO  fuse_query] FuseQuery is shutting down. Try to wait 5 seconds for the currently executing query. You can press Ctrl + C again to force shutdown.
[2021-06-25T00:37:41Z TRACE mio::poll] deregistering event source from poller
Jun 25 08:37:41.097 DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
Jun 25 08:37:41.097 DEBUG hyper::server::shutdown: signal received, starting graceful shutdown
[2021-06-25T00:37:41Z TRACE mio::poll] deregistering event source from poller
[2021-06-25T00:37:41Z TRACE mio::poll] deregistering event source from poller
^X^C[2021-06-25T00:37:42Z INFO  fuse_query] Force Shutting down FuseQuery.
^C^C^C^C^C^C^C^C^C^C^C^C^C^C

```

gdb stacktrace:
```
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) bt
#0  futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x55b3f15ecccc) at ../sysdeps/nptl/futex-internal.h:183
#1  __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x55b3f15ecc70, cond=0x55b3f15ecca0) at pthread_cond_wait.c:508
#2  __pthread_cond_wait (cond=0x55b3f15ecca0, mutex=0x55b3f15ecc70) at pthread_cond_wait.c:638
#3  0x000055b3eea81a4a in std::sys::unix::condvar::Condvar::wait (self=0x55b3f15ecca0, mutex=0x55b3f15ecc70) at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/sys/unix/condvar.rs:71
#4  0x000055b3eeab382e in std::sys_common::condvar::Condvar::wait (self=0x55b3f15ecd08, mutex=0x55b3f15eccf8) at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/sys_common/condvar.rs:44
#5  0x000055b3eea3e9b1 in std::sync::condvar::Condvar::wait (self=0x55b3f15ecd08, guard=...) at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/sync/condvar.rs:187
#6  0x000055b3eea96dee in tokio::park::thread::Inner::park (self=0x55b3f15eccf0) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:112
#7  0x000055b3eea97cbc in <tokio::park::thread::CachedParkThread as tokio::park::Park>::park::{{closure}} (park_thread=0x7f61a58d2a68)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:281
#8  0x000055b3eea97736 in tokio::park::thread::CachedParkThread::with_current::{{closure}} (inner=0x7f61a58d2a68) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:249
#9  0x000055b3eea5120b in std::thread::local::LocalKey<T>::try_with (self=0x55b3f04f62f8, f=...) at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/thread/local.rs:400
#10 0x000055b3eea97666 in tokio::park::thread::CachedParkThread::with_current (self=0x7fff28bedd78, f=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:249
#11 0x000055b3eea97c4e in <tokio::park::thread::CachedParkThread as tokio::park::Park>::park (self=0x7fff28bedd78)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:281
#12 0x000055b3ece20790 in tokio::park::thread::CachedParkThread::block_on (self=0x7fff28bedd78, f=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/park/thread.rs:267
#13 0x000055b3eced1875 in tokio::runtime::enter::Enter::block_on (self=0x7fff28bedfb0, f=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/enter.rs:151
#14 0x000055b3ecec4ffd in tokio::runtime::thread_pool::ThreadPool::block_on (self=0x7fff28bee690, future=...)
    at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/thread_pool/mod.rs:71
#15 0x000055b3ece39113 in tokio::runtime::Runtime::block_on (self=0x7fff28bee688, future=...) at /home/bohu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.7.1/src/runtime/mod.rs:452
#16 0x000055b3ece1423d in fuse_query::main () at fusequery/query/src/bin/fuse-query.rs:165
```

**Comment by BohuTANG** [comment]
cc @zhang2014

**Comment by BohuTANG** [comment]
BTW:
This issue https://github.com/datafuselabs/datafuse/issues/903 maybe helpful for testing
